apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod1
  labels:
    env: test
spec:
  containers:
    - name: nginx-container
      image: nginx:latest

## to create a pod with using this
## kubectl create -f pod.yaml
